server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trybe
    username: root
    password: 1234

dbc:
  h2:
    mem: speciality_database
    username: minhas-series
    password: minhas-series!

logging:
  file:
    name: ./logs/minhas-series.log