server:
  port: 8080

spring:
  datasource:
    url: "jdbc:h2:mem:minhas_series_database"
    username: "minhas_series_app"
    password: "minhas_series_app"

resilience4j.circuitbreaker:
  configs:
    default:
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
  instances:
    serie:
      baseConfig: default